### ISSUE TITLE
List of Issues (still incomplete)

### ISSUE THREAD

**Issue by fpsom** [datacarpentry/wrangling-genomics#22]
Incomplete list of significant changes to content that needs to be written and/or revised:

## General
- [x] Deletion of master branch - both files in master branch are present in `gh-pages` so `master` branch could be deleted

## Main page
[GitHub URL](https://github.com/datacarpentry/wrangling-genomics/blob/gh-pages/index.md)
- [x] See [this issue](https://github.com/datacarpentry/wrangling-genomics/issues/29)

## README
[GitHub URL](https://github.com/datacarpentry/wrangling-genomics/blob/gh-pages/README.md)
- [x] There are a few missing links. Check for content

## AUTHORS 
[GitHub URL](https://github.com/datacarpentry/wrangling-genomics/blob/gh-pages/AUTHORS)
- [x] Empty page, needs content

## CITATION
[GitHub URL](https://github.com/datacarpentry/wrangling-genomics/blob/gh-pages/CITATION)
- [x] Empty page, needs content

## Conduct
[GitHub URL](https://github.com/datacarpentry/wrangling-genomics/blob/gh-pages/CONDUCT.md)
- [x] Check links

### README
[GitHub URL](https://github.com/datacarpentry/wrangling-genomics/blob/gh-pages/lessons/README.md)
- [x] Almost empty page

### process_fastqc_results
[GitHub URL](https://github.com/datacarpentry/wrangling-genomics/blob/gh-pages/lessons/process_fastqc_results.sh)
- [x] The script is not structured for execution (free text is interspersed with code). Needs cleaning up.

### run_variant_calling
[GitHub URL](https://github.com/datacarpentry/wrangling-genomics/blob/gh-pages/lessons/run_variant_calling.sh)
 - [x] Script is working fine if the environment is setup correctly. Need to re-check after cleaning up lesson + connecting to the lesson setup.

### Reference
[Site](http://www.datacarpentry.org/wrangling-genomics/reference/)
[GitHub URL](https://github.com/datacarpentry/wrangling-genomics/blob/gh-pages/reference.md)
- [ ] Empty page, needs content

### About
[Site](http://www.datacarpentry.org/wrangling-genomics/about/)
[GitHub URL](https://github.com/datacarpentry/wrangling-genomics/blob/gh-pages/_extras/about.md)
- [x] Empty page, needs content

### Discussion
[Site](http://www.datacarpentry.org/wrangling-genomics/discuss/)
[GitHub URL](https://github.com/datacarpentry/wrangling-genomics/blob/gh-pages/_extras/discuss.md)
- [x] Empty page, needs content

### Figures
[Site](http://www.datacarpentry.org/wrangling-genomics/figures/)
[GitHub URL](https://github.com/datacarpentry/wrangling-genomics/blob/gh-pages/_extras/figures.md)
- [x] Empty page, needs content (figures are not located correctly?)

### Instructor Notes
[Site](http://www.datacarpentry.org/wrangling-genomics/guide/)
[GitHub URL](https://github.com/datacarpentry/wrangling-genomics/blob/gh-pages/_extras/guide.md)
- [ ] Empty page, needs content

### Lesson 0:  Setup
[Site](http://www.datacarpentry.org/wrangling-genomics/setup)
[GitHub URL](https://github.com/datacarpentry/wrangling-genomics/blob/gh-pages/setup.md)
- [x] Decide on whether to use Amazon or not
- [x] Update links to BWA, Samtools, BCFTools to go to manuals (or ...), not github repos
- [x] 'tarball' is jargon to some/many

### Lesson 1: Quality Control
[Site](http://www.datacarpentry.org/wrangling-genomics/00-readQC/)
[GitHub URL](https://github.com/datacarpentry/wrangling-genomics/blob/gh-pages/_episodes/00-readQC.md)

- [x] See [this issue](https://github.com/datacarpentry/wrangling-genomics/issues/23)

### Lesson 2: Variant Calling Workflow
[Site](http://www.datacarpentry.org/wrangling-genomics/01-variant_calling_workflow/)
[GitHub URL](https://github.com/datacarpentry/wrangling-genomics/blob/gh-pages/_episodes/01-variant_calling_workflow.md)

- [x] See [this issue](https://github.com/datacarpentry/wrangling-genomics/issues/25)

### Lesson 3: Automating a Variant Calling Workflow
[Site](http://www.datacarpentry.org/wrangling-genomics/02-automating_a_workflow/)
[GitHub URL](https://github.com/datacarpentry/wrangling-genomics/blob/gh-pages/_episodes/02-automating_a_workflow.md)

- [x] See [this issue](https://github.com/datacarpentry/wrangling-genomics/issues/26)

**Comment by fpsom** [comment]
@lexnederbragt No that's actually great! I think it would be more convenient for the wrap-up to have them all collated in the same place.

**Comment by ErinBecker** [comment]
lessons directory is outdated and can be removed. See https://github.com/datacarpentry/wrangling-genomics/pull/66

**Comment by ErinBecker** [comment]
AUTHORS file is redundant and can be removed. See https://github.com/datacarpentry/wrangling-genomics/pull/65

**Comment by ErinBecker** [comment]
About page is rendering correctly: http://www.datacarpentry.org/wrangling-genomics/about/

**Comment by ErinBecker** [comment]
Moving instructor notes and reference files to new issues and closing here.
