### ISSUE TITLE
Variant Calling Workflow Issue Bonanza

### ISSUE THREAD

**Issue by lexnederbragt** [datacarpentry/wrangling-genomics#25]
## Objectives: 

> Use a For loop from the previous lesson to help automate repetitive tasks

- [x] Remove, as this is not done in this lesson.

## Lesson:

- [x] rephrase learning objectives as 'be able to' etc

- [x] The first commands are misformatted

> NOTE: This only has to be run once. The only reason you would want to create a new index is if you are working with a different reference genome or you are using a different tool for alignment.

- [x] Make it a Callout using the '{: .callout}' syntax? We could use Callout boxes more throughout.

- [x] Explain the general setup of commands, e.g. `bwa aln reference_genome readfile`, see #55 and #56

> The SAM file, is a tab-delimited text file 

- [x] Links to [this github page](https://github.com/adamfreedman/knowyourdata-genomics/blob/gh-pages/lessons/01-know_your_data.md#aligned-reads-sam), find a better alternative.

- [x] Explain why we would want to make a binary version of a file in general, and the SAM file in particular see #57

> Filter the SNPs for the final output in VCF format, using vcfutils.pl:

- [x] Format vcfutils.pl as `vcfutils.pl`

> . IGV requires the .bai file to be in the same location as the .bam file that is loaded into IGV, but there is no direct use for that file.

- [x] Isn't there? See #58

- [x] explain functionality, coloring and GUI elements of IGV in more detail See #59
- [ ] explain how to inspect alignments to see whether a variant is indeed called correctly, maybe point to a variant that did not pass filtering See #60

## Key Points

- [x] missing

**Comment by ErinBecker** [comment]
Some of these items are out of my element. @fpsom @lexnederbragt @crazyhottommy @jrherr would one of you be able to put in a PR(s) to fix the rest of these bullet points?

**Comment by lexnederbragt** [comment]
#55 is addressing part of

> Explain the general setup of commands, e.g. bwa aln reference_genome readfile

I don't know samtools mpileup and bcftools well enough to add descriptions for those. I files a separate issue for that #56

**Comment by lexnederbragt** [comment]
#60 is asking for a fix for

> explain how to inspect alignments to see whether a variant is indeed called correctly, maybe point to a variant that did not pass filtering

**Comment by ErinBecker** [comment]
Thanks for putting together this list @lexnederbragt. Since the only item remaining has its own issue, I'm closing this issue now.
